import { Highlight } from "@tiptap/extension-highlight";
import type MarkdownIt from "markdown-it";
import markdownitMark from "markdown-it-mark";

export default Highlight.extend({
  addStorage() {
    return {
      markdown: {
        serialize: {
          open: "==",
          close: "==",
        },
        parse: {
          setup(markdownit: MarkdownIt) {
            markdownit.use(markdownitMark);
          },
          updateDOM() {
            // You can update HTML generated by markdown-it here
          },
        },
      },
    };
  },
});

