import markdownitMark from "markdown-it-mark";
import type MarkdownIt from "markdown-it";
import Underline from "@tiptap/extension-underline";

export default Underline.extend({
  addStorage() {
    return {
      markdown: {
        serialize: {
          open: "<ins>",
          close: "</ins>",
        },
        parse: {
          setup(markdownit: MarkdownIt) {
            markdownit.use(markdownitMark);
          },
          updateDOM() {
            // You can update HTML generated by markdown-it here
          },
        },
      },
    };
  },
});

